#SQL BAĞLANTISI (Kendi SQL Ayarlarınıza göre güncelleyin.)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=
quarkus.datasource.username=
quarkus.datasource.password= 

quarkus.datasource.devservices.enabled=false

#HİBERNATİVE ORM AYARLARI
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true


quarkus.banner.enabled=false
quarkus.http.port=8080

#CORS AYARLARI
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=Content-Type,Accept,Authorization,X-Requested-With
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=24H

#LOG AYARLARI
quarkus.log.level=INFO
quarkus.log.category."com.example.fullstack".level=DEBUG

# JWT AYARLARI
mp.jwt.verify.publickey.location=META-INF/publicKey.pem
mp.jwt.verify.issuer=https://vms.example.com
smallrye.jwt.sign.key.location=META-INF/privateKey.pem
